DROP DATABASE IF EXISTS exampledb;
CREATE DATABASE exampledb;

DROP DATABASE IF EXISTS fumblr_db;
CREATE DATABASE fumblr_db;
USE fumblr_db;

CREATE TABLE fumblarts
(
id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
title VARCHAR(255) NOT NULL,
author VARCHAR (140) NOT NULL,
art_link VARCHAR(255) NOT NULL,
description VARCHAR(255),
date_submitted INTEGER NOT NULL,
);
